{
 "title": "Glances",
 "description": "A Glances dashboard for Glances + InfluxDB2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"hostname\",\n    predicate: (r) => true,\n    start: -1d\n)"
   },
   {
    "name": "container",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"name\",\n    predicate: (r) => true,\n    start: -1d\n)"
   },
   {
    "name": "interface",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"interface_name\",\n    predicate: (r) => true,\n    start: -1d\n)"
   },
   {
    "name": "disk",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"disk_name\",\n    predicate: (r) => true,\n    start: -1d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Glances $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Core",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "column": "cpucore",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "load",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"load\" and\n    r._field == \"cpucore\" and\n    r.hostname == \"${host}\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "cpucore" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "1min",
     "column": "min1",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "load",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"load\" and\n    r._field == \"min5\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean5\")\n  \n  ",
     "select": [
      [
       { "params": [ "min1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "randomWalk('random walk')"
    },
    {
     "alias": "1min",
     "column": "min1",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "load",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"load\" and\n    r._field == \"min15\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean15\")\n  \n  ",
     "select": [
      [
       { "params": [ "min1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "randomWalk('random walk')"
    },
    {
     "alias": "1min",
     "column": "min1",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "load",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"load\" and\n    r._field == \"min1\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean1\")\n  \n  ",
     "select": [
      [
       { "params": [ "min1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ],
     "target": "randomWalk('random walk')"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "processcount",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"processcount\" and\n    r._field == \"total\" and\n    r.hostname == \"${host}\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "series": "processcount",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "User",
     "column": "user",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cpu\" and\n    r._field == \"user\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"user\")\n  \n  ",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "System",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cpu\" and\n    r._field == \"system\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"system\")\n  \n  ",
     "select": [
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "IoWait",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cpu\" and\n    r._field == \"iowait\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"iowait\")\n  \n  ",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "User",
     "column": "user",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"gpu\" and\n    r._field == \"mem\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mem\")\n  \n  ",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "System",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"gpu\" and\n    r._field == \"proc\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"system\")\n  \n  ",
     "select": [
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$interface network interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "In",
     "column": "enp0s25.rx",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "$host.network",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"network\" and\n    (r._field == \"rx\" or r._field == \"time_since_update\") and\n    r.interface_name == \"${interface}\" and\n    r.hostname == \"${host}\"\n  )\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> map(fn: (r) => ({ r with _value: (r.rx / r.time_since_update) * 8.0 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"rx_rate\"})\n",
     "select": [
      [
       { "params": [ "eth0.rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "network"
    },
    {
     "alias": "Out",
     "column": "eth0.tx*-1",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "$host.network",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"network\" and\n    (r._field == \"tx\" or r._field == \"time_since_update\") and\n    r.interface_name == \"${interface}\" and\n    r.hostname == \"${host}\"\n  )\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> map(fn: (r) => ({ r with _value: (r.tx / r.time_since_update) * -8.0 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"tx_rate\"})\n",
     "select": [
      [
       { "params": [ "eth0.tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "network"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"mem\" and\n    r._field == \"used\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"used\")\n  \n  ",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max",
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"mem\" and\n    r._field == \"total\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"total\")\n  \n  ",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$disk disk IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Read",
     "column": "sda2.read_bytes",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$host.diskio",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"diskio\" and\n    (r._field == \"read_bytes\" or r._field == \"time_since_update\") and\n    r.disk_name == \"${disk}\" and\n    r.hostname == \"${host}\"\n  )\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> map(fn: (r) => ({ r with _value: (r.read_bytes / r.time_since_update) }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"read_rate\"})\n",
     "select": [
      [
       { "params": [ "sda2.read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "diskio"
    },
    {
     "alias": "Write",
     "column": "sda2.write_bytes",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$host.diskio",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"diskio\" and\n    (r._field == \"write_bytes\" or r._field == \"time_since_update\") and\n    r.disk_name == \"${disk}\" and\n    r.hostname == \"${host}\"\n  )\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> map(fn: (r) => ({ r with _value: (r.write_bytes / r.time_since_update) * -1.0 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"write_rate\"})\n",
     "select": [
      [
       { "params": [ "sda2.write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "diskio"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "$host.memswap",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"memswap\" and\n    r._field == \"used\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"used\")\n  ",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "memswap"
    },
    {
     "alias": "Max",
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "$host.memswap",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"memswap\" and\n    r._field == \"total\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"total\")\n  \n  ",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "memswap"
    }
   ]
  },
  {
   "title": "/ Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used",
     "column": "\"/.used\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fs",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fs\" and\n    r._field == \"used\" and \n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"used\")\n  \n  ",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs",
     "tags": [
      { "key": "mnt_point", "operator": "=", "value": "/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Max",
     "column": "\"/.size\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fs",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fs\" and\n    r._field == \"size\" and \n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"size\")\n  \n  ",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs",
     "tags": [
      { "key": "mnt_point", "operator": "=", "value": "/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "/ used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "column": "\"/.percent\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fs",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"fs\" and\n    r._field == \"percent\" and\n     \n    r.hostname == \"${host}\"\n  )\n  |> last()\n",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs",
     "tags": [
      { "key": "mnt_point", "operator": "=", "value": "/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Sensors $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GPU temperature",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "alias": "AmbientTemperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"gpu\" and\n    r._field == \"temperature\" and\n\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Ambient\")\n  \n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=", "value": "Ambient" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "alias": "CpuTemperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"sensors\" and\n    r._field == \"value\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Ambient\")\n  \n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=", "value": "CPU" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Containers hosted on $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$container container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "MEM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"containers\" and\n    r._field == \"memory_usage\" and\n    r.name == \"${container}\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"MEM\")\n  \n  ",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "CPU%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker",
     "query": "from(bucket: \"glances\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"containers\" and\n    r._field == \"cpu_percent\" and\n    r.name == \"${container}\" and\n    r.hostname == \"${host}\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"CPU%\")\n  \n  ",
     "select": [
      [
       { "params": [ "cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}